project_name: gtunnel

release:
  github:
    owner: B-AJ-Amar
    name: gtunnel

builds:
  - id: gtunnel-client
    main: ./cmd/client
    binary: gtc
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - "386"
      - arm64
    env:
      - CGO_ENABLED=0
    dir: .
    ldflags:
      - -s -w
      - -X github.com/B-AJ-Amar/gTunnel/internal/pkg.Version={{.Version}}
      - -X github.com/B-AJ-Amar/gTunnel/internal/pkg.GitCommit={{.ShortCommit}}
      - -X github.com/B-AJ-Amar/gTunnel/internal/pkg.BuildDate={{.Date}}
      - -X github.com/B-AJ-Amar/gTunnel/internal/pkg.GoVersion=1.23.5

  - id: gtunnel-server
    main: ./cmd/server
    binary: gts
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - "386"
      - arm64
    env:
      - CGO_ENABLED=0
    dir: .
    ldflags:
      - -s -w
      - -X github.com/B-AJ-Amar/gTunnel/internal/pkg.Version={{.Version}}
      - -X github.com/B-AJ-Amar/gTunnel/internal/pkg.GitCommit={{.ShortCommit}}
      - -X github.com/B-AJ-Amar/gTunnel/internal/pkg.BuildDate={{.Date}}
      - -X github.com/B-AJ-Amar/gTunnel/internal/pkg.GoVersion=1.23.5

archives:
  - id: client-archive
    builds:
      - gtunnel-client
    format_overrides:
      - goos: windows
        format: zip
    format: tar.gz
    name_template: "{{ .ProjectName }}-client_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    wrap_in_directory: true

  - id: server-archive
    builds:
      - gtunnel-server
    format_overrides:
      - goos: windows
        format: zip
    format: tar.gz
    name_template: "{{ .ProjectName }}-server_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    wrap_in_directory: true

nfpms:
  - id: linux-packages
    formats:
      - deb
      - rpm
    bindir: /usr/bin
    builds:
      - gtunnel-client
      - gtunnel-server
    section: default
    maintainer: "B-AJ-Amar <amarbouakaz91@gmail.com>"
    description: "gTunnel is a fast, lightweight tunneling solution"
    license: MIT
    homepage: "https://github.com/B-AJ-Amar/gTunnel"

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ .Tag }}-next"

before:
  hooks:
    - go mod tidy
    - go test ./...
