name: GoReleaser Check

on:
  push:
    paths:
      - '.goreleaser.yml'
      - '.goreleaser.yaml'
  pull_request:
    paths:
      - '.goreleaser.yml'
      - '.goreleaser.yaml'

jobs:
  goreleaser-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: stable

      - name: Check GoReleaser config
        uses: goreleaser/goreleaser-action@v5
        with:
          distribution: goreleaser
          version: latest
          args: check
